### ISSUE TITLE
Aur installation with yay does not pass validity check

### ISSUE THREAD

**Issue by Dooez** [contour-terminal/libunicode#103]
When installing contour from aur using yay building libunicode fails with error `ERROR: One or more files did not pass the validity check`.
Edit: I've assumed that this is the correct place to submit an issue because contour page has a link to aur. If i am mistaken i'm sorry for an inconvenience.

**Comment by Yaraslaut** [comment]
Hi @Dooez, no worries we know whom to contact to get things fixed

**Comment by Yaraslaut** [comment]
Hi @Dooez 
Now libunicode in the main arch repo https://archlinux.org/packages/extra/x86_64/libunicode
So i suppose we can close this one
