### ISSUE TITLE
create release (0.1.0)

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/libunicode#4]
it's used by contour which is used by quite some people already and stress-tested via [notcurses](https://github.com/dankamongmen/notcurses) demo and other tests. It may be time for a release now.

### Checklist

- [ ] installed package must expose version number. apps using this library must have a way to require that specific version number (or greater).
- [x] create `Changelog.md` for future releases (containing state at first release)
- [ ] maybe reuse release CI script from contour to autogen releases and release pages?
- [ ] create small blog post about on my tiny dev.to :)

**Comment by abenson** [comment]
A release would be appreciated.  That is the issue holding it back from being included in Void Linux: [the guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements) require that there be a "ready for public" release.

**Comment by christianparpart** [comment]
Many thanks. I can do that. With the latest release of Contour and the therefore implied changes to libunicode, I will happy to do that ASAP. :)

**Comment by christianparpart** [comment]
Hey @abenson . I've just released [libunicode 0.1.0](https://github.com/contour-terminal/libunicode/releases/tag/v0.1.0).

It's not just a library, even though that's the main part, but I've also added a CLI tool named `unicode-query` that provides Unicode property access from the command line, so people are not forced to use websites, providing a similar experience.

libunicode itself is currently only built as static library for a reason, but it might make sense (in future releases) to also provide a shared object, depending on how many other tools are using it.

If there is anything else you need from me, just ping me in this ticket, even though I'm about to closes this as "release is done". You can also head over to our Discord for some more realtime communicatioin.

Have a nice day. ;)

**Comment by christianparpart** [comment]
p.s.: despite the version number looking quite low, don't be confused by it. It's used by Contour since about two and a half years already. I so far just never actively tagged a release for libunicode. But it's a very good thing I finally did. So thanks for pushing me. :)
