### ISSUE TITLE
unicode/utf8.h conflicts with ICU

### ISSUE THREAD

**Issue by berolinux** [contour-terminal/libunicode#77]
Trying to install libunicode as a system library in `/usr` results in utf8.h living in `/usr/include/unicode/utf8.h` -- but that file is also owned by the system library installation of ICU.
This makes it impossible to install libunicode and ICU in the same location.

**Comment by christianparpart** [comment]
Hey, many thanks for your interest. I thought we've renamed the include to `<libunicode/...>`.

At least for Fedora (which comes with latest release of libunicode, it already is the case. I am assuming you installed from source, right? Let me check ASAP.

**Comment by christianparpart** [comment]
Okay, I can't spot the error just by looking at the [source](https://github.com/contour-terminal/libunicode/blob/master/src/libunicode/CMakeLists.txt), I'll attempt a manual install soon verify. What git tag did you install from? What is the latest git commit? (I assume latest master)...

**Comment by christianparpart** [comment]
I just wanted to show my output, as it works locally. Yeah. 

However, I always suggest to use releases. But apparently I should create a new release for libunicode. Will do that ASAP.

p.s.: Great to hear about OpenMandriva's adoption. I assume you're doing it on par with Contour then? 😄 🙇

**Comment by christianparpart** [comment]
Update: the latest release of libunicode contains a change that is not yet compatible with the latest release of contour.

The libunicode git SHA we're using is `b1b017c466038655872e1968acfc6a9880cf5d9f`. This works with Contour 0.3.12. I think that is what Fedora might be using (this tag contains the path changes you experienced as well).

So my recommendation would be to use libunicode's git SHA `b1b017c466038655872e1968acfc6a9880cf5d9f` for now, which is pre libunicode 0.3.0 (containing the breaking change).

For the future: Contour will soonish (this year) bump to its next major release, Contour 0.4.0, and there we'll bump libunicode accordingly to its latest stable release.

If you need any help, or would love to give us feedback, please feel free to join us on Discord.

**Comment by christianparpart** [comment]
This can now be safely closed, because the include directory has been renamed to libunicode and contour works with a tagged release of libunicode.
