### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/libunicode#79]
Support for `file(ARCHIVE_EXTRACT ...` was introduced in 3.18, while ubuntu 20.04 support only 3.16 :) 
https://packages.ubuntu.com/focal/cmake
https://cmake.org/cmake/help/latest/command/file.html#archive-extract

**Comment by christianparpart** [comment]
Uff, but don't we have an up-to-date version of CMake on Github CI?

**Comment by Yaraslaut** [comment]
See for example https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
cmake installed manually in the ub 20.04 image

**Comment by christianparpart** [comment]
I think it is okay for CMake to require a newer version than Ubuntu 18/20.04 do provide for as long as we can provide binary packages for these platforms through Github CI. Or what is your stance on this?

OTOH, maybe we can get rid of `file(ARCHIVE_EXTRACT...)` alltogether by embedding fetching the UCD.zip from within the scripts/fetch-ucd.{sh,ps} or so (which would then be executed via cmake

**Comment by Yaraslaut** [comment]
> I think it is okay for CMake to require a newer version than Ubuntu 18/20.04 do provide for as long as we can provide binary packages for these platforms through Github CI. Or what is your stance on this?
> 
> OTOH, maybe we can get rid of `file(ARCHIVE_EXTRACT...)` alltogether by embedding fetching the UCD.zip from within the scripts/fetch-ucd.{sh,ps} or so (which would then be executed via cmake

i think embedding it might be a good idea so we don't create multiple places to fetch dependencies across projects
